### ISSUE TITLE
Possibility to hide parts of text in the commentary.

### ISSUE THREAD

**Issue by Ycreak** [Ycreak/OpensourceClassicCommentary#148]
For example, the apparatus criticus might want to have the apparatus itself first, then an explanation and discussion on _show more_. We must discuss how to add such a directive via the dashboard.

**Comment by sajvanwijk** [comment]
I've implemented a way to do this via a custom [hidden] tag that you add via the dashboard. 
It also works in such a way that is doesn't conflict with the basic hide/unhide functionality of #143:
If it finds a [hidden] tag in the text, it will hide all text after that point. If not, it will simply hide all text after 
a certain point as per #143. 

I still however need to:
- [ ] Add a button for this to the wysiwyg editor
- [ ] Add a tooltip to this button, as it's purpose might be a bit unclear otherwise
