### ISSUE TITLE
Maybe it would be more fitting to rename fragment_name to fragment_number?

### ISSUE THREAD

**Issue by sajvanwijk** [Ycreak/OpensourceClassicCommentary#46]
Maybe something to do at some point

**Comment by Ycreak** [comment]
We have to refactor every fragment_number to fragment_name. First it was an integer, but then Warmington decided to name fragments 355-357 for example, which is a string. Also, there will be editors in the future who will name fragments Bert and/or Ernie because they hate programmers, so now it is a string called fragment_name :D This will be refactored in future when Philippe's patch is ready.
